Repository CAnBioNet/TkNA, pull requests merged in 2023-07, with the labels that each got.

#17 Add argument to parallelized scripts to control number of cores used
  random_networks/compute_network_stats.py
  random_networks/create_random_networks.py
  reconstruction/reconstruction/NetworkReconstructorAggregate.py
  reconstruction/reconstruction/NetworkReconstructorSingleCell.py
  reconstruction/run.py
Labels: enhancement, tkna

#31 Fix calculation of fold change percent agreement for aggregate data
  reconstruction/reconstruction/NetworkReconstructorAggregate.py
Labels: bug, tkna

#33 CSV input and BiBC list
  analysis/assess_network.py
  analysis/calc_network_properties.py
Labels: enhancement, tkna

#35 Louvain partitions on just each data type, and can import network fro…
  analysis/louvain_partition.py
Labels: enhancement, tkna

#37 Labels on KDE plot no longer overlap
  visualization/plot_density.py
Labels: enhancement, tkna

#38 find_all_shortest_paths_bw_subnets.py uses either csv or pickle file as input
  analysis/find_all_shortest_paths_bw_subnets.py
Labels: enhancement, tkna

#39 Fix metatreatment selection
  reconstruction/reconstruction/NetworkReconstructorAggregate.py
  reconstruction/reconstruction/NetworkReconstructorSingleCell.py
Labels: bug, sc, tkna

#41 Specify colors for groups
  visualization/plot_abundance.py
Labels: enhancement, tkna

#48 Update example commands to match current script argument sets
  example_datasets_and_commands/microbiome_and_phenotype/input/example_commands.txt
  example_datasets_and_commands/toy_network/input/example_commands.txt
Labels: documentation, tkna

#47 Update documentation to reflect change in data format from NetCDF to ZIP
  README.md
  example_datasets_and_commands/microbiome_and_phenotype/input/example_commands.txt
  example_datasets_and_commands/toy_network/input/example_commands.txt
  reconstruction/intake_data.py
Labels: documentation, tkna

#49 Ensure node names are converted to strings before contatenation in dot plot script
  visualization/dot_plots.py
Labels: bug, tkna, visualization

#50 Ignore nodes that don't appear in the final network in dot plots script
  visualization/dot_plots.py
Labels: bug, tkna, visualization

#51 Use correct icons in legend in abundance plots
  visualization/plot_abundance.py
Labels: bug, tkna, visualization

#52 Make the colorbar always show the 'High' tick in density plots
  visualization/plot_density.py
Labels: bug, tkna, visualization

#45 Raise exception during intake if input data contains negative values
  reconstruction/intake/Aggregate.py
  reconstruction/intake/SingleCell.py
Labels: bug, sc, tkna

#44 Add config option 'noPUC' to disable PUC in network reconstruction
  reconstruction/reconstruction/NetworkReconstructorAggregate.py
  reconstruction/reconstruction/NetworkReconstructorSingleCell.py
  reconstruction/to_csv.py
  reconstruction/util/configs/Aggregate.py
  reconstruction/util/configs/SingleCell.py
Labels: enhancement, sc, tkna

#54 Update example command for louvain clustering to match changes to arguments
  example_datasets_and_commands/microbiome_and_phenotype/input/example_commands.txt
Labels: documentation, tkna

#46 Gives shared memory an ID corresponding to its runner to avoid conflicts between runs
  reconstruction/reconstruction/NetworkReconstructorAggregate.py
  reconstruction/reconstruction/NetworkReconstructorSingleCell.py
Labels: bug, sc, tkna

#56 Upgrade scipy from 1.8.0 to 1.10.1 due to vulnerability in older versions of scipy
  reconstruction/reconstruction/NetworkReconstructorAggregate.py
  reconstruction/reconstruction/NetworkReconstructorSingleCell.py
  requirements.txt
Labels: dependencies

#57 Dot plots specify output dir
  visualization/dot_plots.py
Labels: enhancement, tkna, visualization

#58 calculate assessment properties per data type
  analysis/assess_network.py
Labels: enhancement, tkna

#59 infomap - added user-specified output directory
  analysis/infomap_assignment.py
Labels: enhancement, tkna

#60 louvain - added user-specified output directory
  analysis/louvain_partition.py
Labels: enhancement, tkna

#61 All shortest paths user specified output directory
  analysis/find_all_shortest_paths_bw_subnets.py
Labels: enhancement, tkna

#62 calc_network_properties - added user-specified output directory
  analysis/calc_network_properties.py
Labels: enhancement, tkna

#64 Use updated version of pearson constant input warning from scipy
  reconstruction/reconstruction/NetworkReconstructorAggregate.py
Labels: bug, tkna

#63 Prevent text from overlapping in dot plots
  visualization/dot_plots.py
Labels: enhancement, tkna, visualization

#15 In error message, differentiate between node groups not being in map and not being in giant component
  random_networks/compute_network_stats.py
Labels: bug, tkna

#67 Upgrade Pillow from 9.0.0 to 9.2.0 due to vulnerabilities in older versions of Pillow
  requirements.txt
Labels: dependencies

#69 Update requirements to resolve vulnerabilities in older versions of some packages
  requirements.txt
Labels: dependencies

#70 Version 1.1.0
  README.md
  analysis/assess_network.py
  requirements.txt
Labels: version release
